name: CI/CD Pipeline

on:
  push:
    branches:
      - main   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Build Docker image
        run: docker build -t simpleweb .

      - name: Run container for testing
        run: docker run -d -p 8080:8080 simpleweb

      

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip deployment package
        run: zip -r deploy.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "simpleweb"       
          environment_name: "Simpleweb-env"   
          version_label: "v-${{ github.sha }}"
          region: "eu-central-1"
          deployment_package: deploy.zip
